name: Build and Deploye 

on: ["push","pull_request"]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hai to ganesh
        run: echo "Hello ganesh"
      - name: Install Python version 3.11
        uses: actions/checkout@v2
        with: 
          python-version: "3.11"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Installing Depedencies
        run: pip install -r requirements.txt