name: Build and Deploye 

on: ["push","pull_request"]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hai to ganesh
        run: echo "Hello ganesh"